### PR TITLE
add printing current DateTime capability (opt-in)

### PR DESCRIPTION
**Pull request by toshi0383**
I needed it, so I added it for myself anyways.
How do you think ?

### CODE REVIEW

**Comment by inamiy** [comment]
Thanks for pull request :smile: 

Though we can basically customize `var printHandler` to whatever format and logging-destination we want, supporting datetime printing by default seems a better improvement, so I'm :+1: to this patch.

On the other hand, I don't think we need any further customizable `Config` type. Instead, we can just use fixed `dateFormat`. Also, it is good practice to prepare costy `NSDateFormatter` before every printing.

**Comment by inamiy** [comment]
Added commit 16ddef5 in `pr6-improvement` branch.
How about this?

**Comment by toshi0383** [comment]
Cool !!
Maybe you want to make `var printHandler` public, so we can customize it from outside the module ?

**Comment by inamiy** [comment]
Thanks for pointing out this! I updated it in b2beb30.
I will merge this pull request first.

**Comment by toshi0383** [comment]
🙌

**Pull request merged**
